### ISSUE TITLE
Sales Tax not calculating correctly in Cart2Quote Extension

### ISSUE THREAD

**Issue by danmorin** [onepica/avatax#109]
Sales tax worked correctly using extension 2.6.0 or older.  Versions newer than 2.6.0 no longer cause sales tax to be calculated in Quotes when using Cart2Quote.  It works correctly on the order screen and when creating an order, but once you create a quote, the tax total gets set to $0.00.

I realize this could be their issue, but because it was an upgrade to this extension that is causing it to no longer work, I was hoping you may have a good idea of what needs to be fixed in order to get it working again.  Thanks,

**Comment by rredko-sysiq** [comment]
Please send your request to support@avalara.com and we will review it. Please provide details how to reproduce issue, actual result and expected result.
