### ISSUE TITLE
unpaid invoices slipping into queue

### ISSUE THREAD

**Issue by artwells** [onepica/avatax#13]
If a PayPal Express order is created, the taxes are queued in the Avatax Order Sync Queue, even before Paypal approves the payment.  This is fine except in circumstances in which the Payment is denied by Paypal, or later the customer.

Changes to salesOrderInvoiceSaveAfter in OnePica_AvaTax_Model_Observer  will prevent this.  Expect a pull request

**Comment by grikka** [comment]
Fixed with https://github.com/onepica/avatax/pull/21

Thanks!
