### ISSUE TITLE
Tax applied after discount calculation issue

### ISSUE THREAD

**Issue by tim-reynolds** [onepica/avatax#138]
We have run into an issue with your Avalara Tax module that we are hoping you can help us with. 

It seems (given the version of Magento we are using) that we are hitting an issue with 100% discounts on carts when the store currency is not the same as the base currency. The issue is with rounding and with tax. 

We found we can solve this issue when we set the Tax to apply BEFORE the discount is applied. 

What does that have to do with you? Normally, nothing. However, your module actually removes the ability to change the order of application for Tax and Discounts. The actual System Configuration goes away when your module is enabled, and you can see where the actual forced override happens in the following source file:

https://github.com/onepica/avatax/blob/7afd37806aae534371e07f698712a6d0e37832c5/app/code/community/OnePica/AvaTax/Helper/Tax/Data.php#L122-L128

The comment on that method is curious, but most of all we really need to know if it will be possible at some point (or already is on a newer version) to apply our tax before the discounts? 

What are the implications? Why is this a limitation? 

We are prepared to modify the module ourselves, but we wanted to check with you about this restriction before we did. 

I also found this issue opened in 2014 that seems to reference the same issue: 
https://github.com/onepica/avatax/issues/9

**Comment by rredko-sysiq** [comment]
Currently we support only tax calculation after discount is applied. That's why setting in admin is disabled. We can investigate your issue. Please send request to support@avalara.com with detailed steps to reproduce, actual result, expected result, extension version and magento version.

**Comment by jgulledge19** [comment]
@tim-reynolds @rredko-sysiq Any update on this? I think we have the same issue. I create a coupon for $50 and apply to shipping set to Yes. If the product is say $33.94 and shipping is say $11.48 which totals $45.42 and current tax rate is 7% should result in a $0 total but it is $0.80.

See screen shot:
![tax-issue](https://cloud.githubusercontent.com/assets/671767/12462062/4c9ec690-bf8a-11e5-8802-67fc80692728.png)

**Comment by JananiKrishnan** [comment]
Hi ,

I am also having the same issue. Can you please update on this issue?

**Comment by YuraZabolotny** [comment]
I have the same issue. Can we get an update?
