### ISSUE TITLE
Quote containing virtual items does not calculate tax without valid shipping address

### ISSUE THREAD

**Issue by aligentjim** [onepica/avatax#16]
If I have a quote containing only virtual items, Magento does not require the customer to enter a shipping address during checkout.  The Onepica_Avatax extension does not calculate tax on this quote because of https://github.com/onepica/avatax/blob/develop/app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address/Total/Tax.php#L59 which looks for an actionable shipping address.  

The `collect()` method on the `OnePica_AvaTax_Model_Sales_Quote_Address_Total_Tax` model is called once per address on the quote.  Physical items are assigned to the shipping address, while virtual items are assigned to the billing address.  

Line 59 is hardcoded to use the shipping address to determine if the address is actionable, regardless of which address Magento is currently collecting totals for.  On a quote containing only virtual items, there isn't a shipping address, which means that the billing address (even though it may be complete, and valid) is never considered actionable.  Consequently, a quote with all virtual items never calculates tax.

The fix for this is to change line 59, which currently reads:
```
if(Mage::helper('avatax')->isAddressActionable($address->getQuote()->getShippingAddress(), $address->getQuote()->getStoreId())){ //Added check for calculating tax for regions filtered in the admin
```
... to...
```
if(Mage::helper('avatax')->isAddressActionable($address, $address->getQuote()->getStoreId())){ //Added check for calculating tax for regions filtered in the admin
```
... so that we're checking to see if the address we're collecting a total for is actionable rather than the shipping address.

I've made this change to test things out locally, and this solves the immediate problem.  Reading through the remainder of the code, the `$address` variable is used everywhere else that the address or related information is required.  So we shouldn't duplicate tax calculations for gift wrap, etc.

I can't see that this change introduces any new problems, and I'm happy to make this change in Aligent's fork of the module and submit a PR.  Is there any reason why this was coded to always use shipping address originally that would make changing this a bad idea?

**Comment by grikka** [comment]
Fixed in https://github.com/onepica/avatax/pull/20

Thanks!
