### ISSUE TITLE
Not saving tax rates to sales_order_tax

### ISSUE THREAD

**Issue by sevenpixels** [onepica/avatax#160]
Tax rates do not get saved when an order is created. Mage_Tax_Model_Observer::salesEventOrderAfterSave pulls the applied taxes and then loops through them all to save the data to the sales_order_tax table.

This poses a problem when trying to look up the break down in taxes after an order has been placed. Specifically for me, looking at Canadian orders and the breakdown of taxes. We need to show the full summary in emails and for the business. But currently only the full summary is available on the cart and checkout pages. After an order is placed the only information available is the tax_amount field in the order table, which is the total tax amount. It would be beneficial to be able to look at the individual tax rates saved in sale_order_tax.

If AvaTax would set the applied taxes, Magento would pick them up and save them automatically.

**Comment by rredko-sysiq** [comment]
Avalara doesn't provide jurisdiction rates per items what is required to display tax details for an order.

**Comment by sevenpixels** [comment]
Not per item, but per order it does. Look at the screenshots provided. I turned on show full summary in the Config -> Taxes -> Cart Display Settings.

Currently, all that is saved to the order is the tax_amount which is the total. But in the screenshots you see there is a breakdown of Canada GST and British Columbia PST. By default Magento saves these tax rates to the quote address object. Then when the quote is converted to an order Magento pulls these applied taxes and loops through them to save them in the sales_order_tax table.

However, since AvaTax took over all the tax stuff it doesn't save any of the tax rates to the quote address object. Since there is nothing in that object, the individual tax rates per order are not saved to the sales_order_tax table.

Here is what is returned from Avatax when looping through the taxes to display on the cart or checkout page. You can see there are multiple rates. This one happens to be for California. There is a CA State tax, CA County tax, and a CA Special tax.
![upload](https://cloud.githubusercontent.com/assets/502377/11596418/c486d878-9a69-11e5-8abf-db7075b1ce83.png)

This is a screenshot showing the different rates being displayed on the cart page.
![screenshot-2015-12-04 09-23-14](https://cloud.githubusercontent.com/assets/502377/11596245/c0879128-9a68-11e5-8d75-b7d62d25dffc.png)

This is a screenshot showing the different rates being displayed on the checkout page.
![screenshot-2015-12-04 09-22-47](https://cloud.githubusercontent.com/assets/502377/11596244/c086fd44-9a68-11e5-859c-140ed7d8fccb.png)

**Comment by rredko-sysiq** [comment]
To display tax details on order level we need to store information about each jurisdiction in sales_order_tax_item which is not possible with response from Avalara. That's why we display tax details only in shopping cart
