### ISSUE TITLE
Composer install issue

### ISSUE THREAD

**Issue by amansilla** [onepica/avatax#215]
I think there are a mistake on all stable versions of this packages since it requires non-stable version of the magento-hackathon/magento-composer-installer. The result is that if you have a project with already requires a stable version of the composer-installer which is totally right, you can't add the avatax package without explicitly update the magento-hackathon/magento-composer-installer to dev-master what I guess is an issue, since stable project should not require non-stable versions of a given dependency.

For example given the following composer.json of a project:

    {
        "name": "foo-project",
        "require": {
            "magento-hackathon/magento-composer-installer": "^3.0"
        }
    }
And composer is executed in order to add the onepica/avatax package:

    $ composer require onepica/avatax

the following error is displayed:

````
Problem 1
    - Installation request for onepica/avatax ^3.0 -> satisfiable by onepica/avatax[3.0.0-stable].
    - onepica/avatax 3.0.0-stable requires magento-hackathon/magento-composer-installer dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
````

Before to create a pull request I'd like to know what the people here means about it.

**Comment by marynychsv** [comment]
We have created internal issue and include fix in future releases.
