### ISSUE TITLE
Wrong grand total in invoice PDF

### ISSUE THREAD

**Issue by dyron** [onepica/avatax#223]
With the 3.0 update the grand total in the generated invoice pdf doesn't include the tax, even "Include Tax In Grand Total" is "Yes".
PDF:
![bildschirmfoto 2016-03-08 um 17 55 06](https://cloud.githubusercontent.com/assets/116693/13608873/ec664260-e556-11e5-91ef-970a80d1efd1.png)
Mail:
![bildschirmfoto 2016-03-11 um 17 06 37](https://cloud.githubusercontent.com/assets/116693/13707802/b06956b0-e7ab-11e5-9edc-8df17b30f89a.png)

**Comment by marynychsv** [comment]
Please provide screenshot of :
- Admin -> System / Configuration -> Sales / Tax -> Calculation Settings
- Admin -> System / Configuration -> Sales / Tax -> Shopping Cart Display Settings
- Admin -> System / Configuration -> Sales / Tax -> Orders, Invoices, Credit Memos Display Settings
Please also provide pdf of your invoice.

**Comment by dyron** [comment]
Configuration:
![bildschirmfoto 2016-03-11 um 16 56 57](https://cloud.githubusercontent.com/assets/116693/13707538/6c85eca2-e7aa-11e5-9f13-e6b000c9824d.png)

Above the screenshot is from the pdf. Do you need the whole one?

**Comment by dyron** [comment]
Got it.

We had to set "Yes" to "Display only one Grand Total" in Admin -> System / Configuration -> Sales / PDF Print-outs.
