### ISSUE TITLE
Not compatible with PHP 7.0.4?

### ISSUE THREAD

**Issue by mrlerch** [onepica/avatax#224]
Keep getting:
Unfortunately, we could not calculate tax for your order. Please try again with a different address or contact us to complete your order.

The request is still the same as under PHP 5.5, however the Response comes back with an error an no information.

Can you please fix that? If you need me to do anything (like generate a log, or what not) then please let me know exactly what you would like me to do and I will get it to you. Thanks.

**Comment by marynychsv** [comment]
Please observe our requirements here :
http://astoundcommerce.com/magento-extensions/avatax/#prerequisites

According to Magento System Requirements, our plugin compatible only with PHP 5.5.x, PHP.5.4.x
Once Magento will support php7 officially we will upgrade our extension.

**Comment by mrlerch** [comment]
Hello and thanks for letting me know. I have been wondering why your extension is not compatible with the latest PHP versions. It seems to work up to PHP 5.6 but then it stops working properly. Do you have a beta version that I could test that would have the capabilities to run on PHP 7? Please advise.

There is another issue that I would like to bring up, since I am talking to one of the developers.

Is there any way to display the tax rate (percentage) on the Magento cart page where one can calculate shipping and sales tax, like:   

Tax (8.6%)     $1.20

I also would like to display my tax like that on the check out / confirmation pages, in orders, and all customer emails and printable. Is there a way of doing that with your extension and Magento?

I operate in the state of Washington with countless tax zones, and all have different tax percentages, and customers pay according to their own tax rate.

Please advise.

**Comment by rredko-sysiq** [comment]
Hi,

Regarding PHP7. We have no beta version and there is no plans to work on this for now. If it is very important you can make request through avalara support (support@avalara.com).

Regarding tax percentage. It's not possible to display tax percentage. You can only enable Display Full Tax Summary option in Tax setting to display detailed tax information http://joxi.ru/gmvjWb5fxw6ZMm.

**Comment by mrlerch** [comment]
Hello, how much would you charge to make this extensions PHP 7 compatible now for Magento 1.9.2.4? Please advise.

**Comment by rredko-sysiq** [comment]
We investigate this issue and will let you know when we can release the fix.

**Comment by mrlerch** [comment]
Thanks for the proposed fix! So I went ahead and made the suggested change:

../lib/AvaTax/classes/GetTaxRequest.class.php, line 85.
change foreach by references :
`foreach($this->Lines as &$line)
{
    $line->registerAddressesIn($this);
}`

To foreach by values:
`foreach($this->Lines as $k=>$line)
{
    $line->registerAddressesIn($this);
    $this->Lines[$k]=$line;
}`

Now the tax quotes are working again. I have not tested it any further, or in production, but it seems to have solved at least the quote issues. Really looking forward to a final and official fix so that PHP 7.0.4 is supported with the Inchoo php7 patch for Magento 1.9.2.4

Thank you!!

Martin
