### ISSUE TITLE
Questions regarding tax percentage display and WA tax location codes

### ISSUE THREAD

**Issue by mrlerch** [onepica/avatax#225]
Hello again. I have more questions and thought I would submit this as a new issue question.

**Issue 1:**
Is there any way to display the tax rate (percentage) on the Magento cart page where one can calculate shipping and sales tax, like:

Tax (8.6%) $1.20

I also would like to display my tax like that on the check out / confirmation pages, in orders, and all customer emails and printable. Is there a way of doing that with your extension and Magento?

I operate in the state of Washington with countless tax zones, and all have different tax percentages, and customers pay according to their own tax rate.

**Issue 2:**
State of Washington has Location codes. For example for my particular address I have location code 3109. This is pretty much not important until it comes to me exporting orders out of Magento into QuickBooks. In my old shopping cart system I save that location code that is returned by State of Washington sales tax connector with the order. When I export my orders I add that code in with the export data. Then I have the entire updated tax table inside QuickBooks and based on the code it assigns the correct tax rate inside QuickBooks.

I would like to see if there is any way to save such location code (if any) with a Magento order, so that I can continue what I have been doing when I export orders from Magento and import them into QuickBooks. 

Please advise.

**Comment by rredko-sysiq** [comment]
Hi Martin,

Will post my answer here also
Issue 1
It's not possible to display tax percentage. You can only enable Display Full Tax Summary option in Tax setting to display detailed tax information http://joxi.ru/gmvjWb5fxw6ZMm.

Issue 2
This issue is not related to our extension. If you need to export some specific data with orders you have to use some 3rd party extension or develop your own export.

Thanks,
Rost

**Comment by mrlerch** [comment]
Hello Rost,

This is regarding issue 2 since issue 1 I think has been answered.

It is important that first and foremost all tax data is saved along with the actual order. I can extract the data and write an order exporter, no problem, but the data, like the State of Washington Location Code needs to be saved with the order in order for me to extract it. Right? I have looked through a tax and shipping quote response and I don't think that the tax code is manifested in that response. I believe it would have to be an actual order. I am just looking for confirmation that Avalara would include the State of Washington tax code with a order tax query. The number I am looking for is 3109 (see below), and want to find out if this will be included when an order is placed using the Avalara response.

If you are not familiar with such tax location code please see here:
http://dor.wa.gov/content/findtaxesandrates/salesandusetaxrates/lookupataxrate/

Sales & Use	 	Motor Vehicle Sales/Rentals	 	Lodging
Retail Sales/Use Tax
Effective dates	1/1/16 - 3/31/16
Location code (view map)	3109
City.........................................	Lake Stevens
County.......................................	Snohomish
State Sales and Use Tax	.065
Local City/County Sales and Use Tax	.021
Total tax rate	.086

Taxable amount	$20.00
Tax due	$1.72
Total due	$21.72
 
Confirmation code	ED586E4B09
Keep this code to confirm the tax rate given for the displayed effective dates.

	
City.........................................	Lake Stevens
County.......................................	Snohomish
Location Code..................................	3109
Regional Transit Authority (RTA)....................	No
Public Transportation Benefit Area (PTBA)............	Snohomish PTBA
Rural County Opportunity Empowerment Zone (CEZ)....	No
Indian Country..................................	No

Check address on map

Thanks.

**Comment by rredko-sysiq** [comment]
Hi Martin,

Can you check Response in Avatax GetTax log and let me know if Avalara return this code and if so in what field.

Thanks,
Rost
