### ISSUE TITLE
Unable to install latest stable module version via composer

### ISSUE THREAD

**Issue by ihor-sviziev** [onepica/avatax#265]
During installing module via composer i've got following error:
```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - onepica/avatax 3.4.0-stable requires onepica/avatax16 ^0.2.2-alpha -> satisfiable by onepica/avatax16[0.2.2-alpha].
    - onepica/avatax 3.4.0-stable requires onepica/avatax16 ^0.2.2-alpha -> satisfiable by onepica/avatax16[0.2.2-alpha].
    - onepica/avatax 3.4.0-stable requires onepica/avatax16 ^0.2.2-alpha -> satisfiable by onepica/avatax16[0.2.2-alpha].
    - Removal request for onepica/avatax16 == 0.2.2.0-alpha
    - Installation request for onepica/avatax ~3.4.0.0 -> satisfiable by onepica/avatax[3.4.0-stable].
```

This issue caused by using alpha version of onepica/avatax16 package in requirement. **Need to use stable version.**

As a workaround I added ```"onepica/avatax16": "^0.2.2-alpha"``` to my composer.json, but it's not real fix.

**Comment by ProxiBlue** [comment]
Wow, a years later, and this issue still exists!

Problem 1
    - onepica/avatax 3.7.0-stable requires onepica/avatax16 ^0.2.2-alpha -> satisfiable by onepica/avatax16[0.2.2-alpha] but these conflict with your requirements or minimum-stability.
    - onepica/avatax 3.7.0-stable requires onepica/avatax16 ^0.2.2-alpha -> satisfiable by onepica/avatax16[0.2.2-alpha] but these conflict with your requirements or minimum-stability.
    - Installation request for onepica/avatax 3.7.* -> satisfiable by onepica/avatax[3.7.0-stable].
