### ISSUE TITLE
Validate Function Issues

### ISSUE THREAD

**Issue by KAB8609** [onepica/avatax#266]
Testing on a EE 1.14.2.1 instance.

app/code/community/OnePica/AvaTax/Model/Sales/Quote/Address.php
Function validate

When a order is coming via the API, the "$this->getQuote()->getStoreId()" is not returning any results resulting in a error. 

Looking at Mage_Sales_Model_Quote_Address it looks like they just do a simple fix which would look like:

`if ($this->getQuote()) {
            if (!$this->_getConfigHelper()->fullStopOnError($this->getQuote()->getStoreId())) {
                return true;
            }
        }`

**Comment by akhoma-astound** [comment]
Thanks for reporting. We will investigate your issue.

**Comment by netalico** [comment]
Any update on this bug? I'm encountering it as well.

**Comment by Zamoroka** [comment]
Hi @KAB8609 and @netalico,

This bug will be fixed in AvaTax 3.5.3 version. We are planning to release this version of extension until the end of this month. 

Thanks for reporting

**Comment by netalico** [comment]
Thanks for the update. Is there any patch you can provide in the meantime to fix this issue?

**Comment by Zamoroka** [comment]
@netalico, unfortunately we can't provide any patches before extension will pass technical review and all tests.

**Comment by netalico** [comment]
What about this instead?

```
if ($this->getQuote()) {
          if (!$this->_getConfigHelper()->fullStopOnError($this->getQuote()->getStoreId())) {
              return true;
          }
        } else {
          if (!$this->_getConfigHelper()->fullStopOnError()) {
              return true;
          }
        }
```

**Comment by Zamoroka** [comment]
Hi all

Avatax 3.5.3 is released.

**Release notes**
- Implemented SOAP Logging for Avatax API transactions.
- Implemented ability to disable normalization during checkout.
- Fixed M1.4 error: Call to undefined method Varien_Date::now().
- Fixed Magento SOAP API Error (quote object absence during order creation).

You can download it from [marketplace](https://marketplace.magento.com/astound-onepica-avatax.html)

Thanks for reporting.
