### ISSUE TITLE
Calculate tax on sales Order

### ISSUE THREAD

**Issue by J-Fricke** [onepica/avatax#267]
We leverage an extension which allows for actual editing of a sale order instead of cancel/re-create. This makes more sense for our business operations. However when enabling the onepica extension it does not calculate tax on changes to the items in the order. 

Tried using instantiating the onepica/avatax calculator, however, everything in those classes are expecting quote objects and not order objects.

**Comment by marynychsv** [comment]
Hello Joshua,

We supports only native magento behaviour and we have to say that cancel/re-create orders is common magento way.
Magento has other documents that depend on order so if you going to make any customization of selling behaviour you have to customize all depended documents.

We can't guarantee that Avatax extension will work with customized checkout or other third party customizations.

**Comment by J-Fricke** [comment]
Ok, we will simply go back to using a manual import in M1 and use the Avalara + Magento extension in M2.

**Comment by marynychsv** [comment]
We currently do not support AvaTax extension for Magento 2 platform. Please use our official communication channel in case you have any questions regarding Magento 1 AvaTax extension.

email: support@avalara.com
documentation: https://astoundcommerce.com/magento-extensions/avatax/
