### ISSUE TITLE
Magento Cron Missing?

### ISSUE THREAD

**Issue by CigarsNMartinis** [onepica/avatax#271]
Hello, went through the repo looking for the cron script for avatax invoice commit on 15 min interval. Cannot locate it! Any help appreciated! Plugin works perfectly, just need the script for commit and we are good to go! Thanks!

**Comment by marynychsv** [comment]
Greetings,

You could find cron settings for AvaTax extension if you browse to https://github.com/onepica/avatax/blob/master/app/code/community/OnePica/AvaTax/etc/config.xml,
line 468.

**Comment by CigarsNMartinis** [comment]
Perfect! Thank you much!
