### ISSUE TITLE
Magento Hackathon Composer Installer dependency should be at "*"

### ISSUE THREAD

**Issue by kirkmadera** [onepica/avatax#45]
This line in your composer.json breaks users' ability to include the Magento Hackathon Composer Installer without specifying a specific version.
```
"magento-hackathon/magento-composer-installer": "dev-master"
```

This forces me to use this line in my composer.json for my project
```
"magento-hackathon/magento-composer-installer": "dev-master as 3.0.4"
```

Which breaks ease of upgrading the composer installer. Chances are, we will forget that we can even upgrade this and will never come back to us, eventually leaving some projects with an older version of the hackathon installer.

Please update this line to as specified here (https://github.com/magento-hackathon/magento-composer-installer):
```
"magento-hackathon/magento-composer-installer": "*"
```

**Comment by rredko-sysiq** [comment]
Yes, in the next release we will update this. Thanks.

**Comment by kirkmadera** [comment]
A note on this. I figured out that my alias was wrong and that it can at least be left open to anything in 3.0.x. If anyone needs this now, the compose version constraint should look like this:

```
"magento-hackathon/magento-composer-installer": "3.0.x-dev as dev-master"
```

**Comment by rredko-sysiq** [comment]
We will move "magento-hackathon/magento-composer-installer" to suggest instead of require. So you can use in your project what you need. It is more correct way.

**Comment by kirkmadera** [comment]
Awesome. Thanks for the quick feedback!
