### ISSUE TITLE
Custom total isn't used for tax calculation

### ISSUE THREAD

**Issue by steverobbins** [onepica/avatax#50]
I've created a new total called "Shipping & Handling Surcharge" that uses custom logic to calculate a fee

![image](https://i.imgur.com/Hh0hG2T.png)

I need this fee to be included when calculating tax.  I think can be done by including it as a line item in the `GetTax` request.  How can I hook onto this even to add a line?

On a related note, how can I add tax to the shipping method?

**Comment by akhoma-astound** [comment]
Avatax extension supports native Magento. We can't guarantee that it will work with 3d party modules that make impact on native magento behaviour. You can try to set collector after tax.
Thanks.

**Comment by ebaschiera** [comment]
Hi,
closing help requests by saying that Avatax supports native Magento doesn't make sense to me. Who uses plain vanilla Magento without 3rd-party extensions nowadays?
IMHO there is a need for "hooks" in Avatax to add taxes to whatever customization we need to implement.
Thanks!
