### ISSUE TITLE
Gift card orders are charging tax

### ISSUE THREAD

**Issue by kalenjordan** [onepica/avatax#7]
I'm seeing gift card orders being charged tax, which I'm pretty sure they shouldn't be...?  By gift card order I mean the order in which the gift card (which is a virtual product) is purchased.

Here's an example request/response:
https://gist.github.com/kalenjordan/d281a226bf91a9ecfc65

I also contacted Avalara about this but have a hunch it may be specific to the module.

**Comment by molotovbliss** [comment]
Same issue with 2.6.6.0 of the module. Is there any resolution to this?

**Comment by rredko-sysiq** [comment]
Hi, please discuss this first with Avalara. If they decide that it is bug from our side then they will contact is to fix.

**Comment by molotovbliss** [comment]
FYI, My Fix for this issue: https://github.com/molotovbliss/avatax/commit/f42a85f9dd5118c106a9797cb5a364e370ad5872
