### ISSUE TITLE
Compatibility Issue with SUPEE-6788 patch

### ISSUE THREAD

**Issue by kidonchu** [onepica/avatax#99]
After security path SUPEE-6788 is applied, admin controller is no longer compatibie with Magento.

Especially following two pages are 404 now.

/avatax/adminhtml_grid/log/
/avatax/adminhtml_grid/queue/

Can we get this patched for AvaTax module?

Thank you.

**Comment by rredko-sysiq** [comment]
Yes, new version will be released today

**Comment by symfonienanis** [comment]
Hi, i fixed the problem of grid controllers after patch .
But i dont know if there is some other issues, and i can't found any update for patch bugs

**Comment by rredko-sysiq** [comment]
The latest 2.6.6-stable version works fine with the latest Magento versions.

**Comment by symfonienanis** [comment]
thanks a lot , can you confirm this in enterprise version too?

**Comment by rredko-sysiq** [comment]
Yes

**Comment by symfonienanis** [comment]
ok
 thanks again
